from pydantic import BaseModel, EmailStr
from datetime import datetime
from typing import List, Optional, Dict, Any
from enum import Enum

# --- Enums for Status and Type Fields ---

class JobStatus(str, Enum):
    """Possible stages for a job posting."""
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"

class CandidateStage(str, Enum):
    """The current stage of a candidate in the pipeline."""
    APPLIED = "APPLIED"
    SCREENING_IN_PROGRESS = "SCREENING_IN_PROGRESS"
    OA_PENDING = "OA_PENDING"
    OA_COMPLETE = "OA_COMPLETE"
    INTERVIEW_PENDING = "INTERVIEW_PENDING"
    HIRED = "HIRED"
    REJECTED = "REJECTED"

class InterviewType(str, Enum):
    """Type of interview."""
    AI_SCREEN = "AI_SCREEN"
    HUMAN_PANEL = "HUMAN_PANEL"

class InterviewStatus(str, Enum):
    """Status of an interview event."""
    PENDING = "PENDING"
    SCHEDULED = "SCHEDULED"
    COMPLETED = "COMPLETED"
    CANCELED = "CANCELED"

class AssessmentStatus(str, Enum):
    """Status of an online assessment."""
    SENT = "SENT"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    GRADED = "GRADED"


# --- 1. Authentication and User Schemas ---

class Token(BaseModel):
    """Response model for a successful login, containing the JWT."""
    access_token: str
    token_type: str = "bearer"

class UserBase(BaseModel):
    """Base model for user identity."""
    email: EmailStr
    full_name: str
    org_id: Optional[str] = None # Will be set on registration/lookup

class UserCreate(UserBase):
    """Model for creating a new user (registration)."""
    password: str
    # Optional organization name provided at signup. If supplied the server
    # will create an organization and associate the user with it.
    org_name: Optional[str] = None

class User(UserBase):
    """Model representing a user fetched from the database."""
    id: str
    is_active: bool = True
    created_at: datetime
    
    class Config:
        from_attributes = True

class Organization(BaseModel):
    """Model for the organization data."""
    id: str
    name: str
    hr_contact_email: EmailStr

    class Config:
        from_attributes = True


# --- 2. Job Post Schemas ---

class JobPostBase(BaseModel):
    """Base data for a job post."""
    title: str
    description: str
    required_skills: List[str]
    min_experience_years: float
    salary_range_min: Optional[int] = None
    salary_range_max: Optional[int] = None

class JobPostCreate(JobPostBase):
    """Model for creating a new job post."""
    pass

class JobPostUpdate(BaseModel):
    """Model for updating an existing job post."""
    title: Optional[str] = None
    description: Optional[str] = None
    required_skills: Optional[List[str]] = None
    status: Optional[JobStatus] = None

class JobPost(JobPostBase):
    """Model representing a job post fetched from the database."""
    id: str
    org_id: str
    status: JobStatus = JobStatus.DRAFT
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


# --- 3. Candidate & AI Screening Schemas ---

class CandidateBase(BaseModel):
    """Base data for a candidate application."""
    full_name: str
    email: EmailStr
    # This URL would point to the stored CV/Resume file
    resume_url: str

class CandidateCreate(CandidateBase):
    """Model for submitting a new candidate application."""
    job_post_id: str

class Candidate(CandidateBase):
    """Model representing a candidate fetched from the database."""
    id: str
    job_post_id: str
    stage: CandidateStage = CandidateStage.APPLIED
    application_date: datetime
    
    class Config:
        from_attributes = True


class ScreeningResult(BaseModel):
    """The result generated by the AI CV Screening model."""
    candidate_id: str
    job_post_id: str
    # AI-generated compatibility score (0.0 to 1.0)
    ai_score: float
    # Short summary of the candidate's profile in relation to the job
    summary: str
    # Detailed analysis structure (e.g., skill-by-skill match, keyword density)
    fit_analysis: Dict[str, Any]
    # Key skills/qualifications that match the job post
    top_matches: List[str]
    # Potential issues or missing requirements
    red_flags: List[str]

    class Config:
        from_attributes = True


# --- 4. Online Assessment (OA) Schemas ---

class AssessmentCreate(BaseModel):
    """Model to trigger the generation and sending of an OA."""
    job_post_id: str
    assessment_topic: str
    number_of_questions: int = 5

class Assessment(BaseModel):
    """Model for an online assessment record."""
    id: str
    candidate_id: str
    job_post_id: str
    status: AssessmentStatus = AssessmentStatus.SENT
    # The actual questions generated by the AI
    generated_questions: List[Dict[str, Any]]
    sent_at: datetime
    completion_link: str # Link for the candidate to take the assessment

    class Config:
        from_attributes = True

class AssessmentResult(BaseModel):
    """The AI-graded result of a completed online assessment."""
    assessment_id: str
    # Overall score out of 100
    overall_score: float
    # Detailed feedback structured by question or criteria
    detailed_feedback: Dict[str, Any]
    # AI summary of the candidate's performance
    ai_analysis: str

    class Config:
        from_attributes = True


# --- 5. Interview Schemas ---

class InterviewSchedule(BaseModel):
    """Model to trigger the AI scheduling agent."""
    interview_type: InterviewType = InterviewType.AI_SCREEN
    # Optional: if a human interviewer is needed
    interviewer_ids: Optional[List[str]] = None
    duration_minutes: int = 60

class Interview(BaseModel):
    """Model for an interview record."""
    id: str
    candidate_id: str
    job_post_id: str
    type: InterviewType
    status: InterviewStatus
    scheduled_time: Optional[datetime] = None
    meeting_link: Optional[str] = None
    # Who is involved in the interview (can be the AI agent ID or human user IDs)
    participants: List[str]

    class Config:
        from_attributes = True

class InterviewTranscript(BaseModel):
    """The full transcript and AI analysis of a completed interview."""
    interview_id: str
    # Full text of the conversation (AI + Candidate)
    transcript_text: str
    # A calculated sentiment score for the candidate's responses
    ai_sentiment_score: float
    # Key actionable points extracted by the AI
    key_insights: List[str]
    # Time it took for the interview
    duration_minutes: int

    class Config:
        from_attributes = True